distillation:
  temperature: 7.0
  alpha: 0.1
  
training:
  epochs: 4
  batch_size: 128
  learning_rate: 0.001

models:
  teacher:
    epochs: 3  # Del notebook original
    
#
output:
  verbose: 1
  model_save_path: "./models"  # o la ruta que prefieras